version: "3"

services:

  app:
    build: ../.
    env_file:
      - ../.env
    container_name: task_2_app
    ports:
      - "9000:8000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: records
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - db_data_task_2:/var/lib/postgresql/data

volumes:
  db_data_task_2:

